# Generated by Django 4.0.4 on 2022-05-16 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_client_adress_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='temp event name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^(0|\\+[1-9]{2})[-., ]?[1-9]?([-., ]?[0-9]{2,}){4,}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^(0|\\+[1-9]{2})[-., ]?[1-9]?([-., ]?[0-9]{2,}){4,}$')]),
        ),
    ]
