# Generated by Django 4.0.4 on 2022-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
