# Generated by Django 4.0.4 on 2022-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_contract_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
