# Generated by Django 4.0.4 on 2022-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_client_comment_event_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
