# Generated by Django 4.0.4 on 2022-05-30 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_alter_employeeclient_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='client',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='employeeevent',
            old_name='client',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='employeeclient',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee assigned'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee assigned'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee assigned'),
        ),
    ]
