# Generated by Django 4.0.4 on 2022-05-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_client_employeecontract_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='events.event'),
        ),
    ]
